## REGRESSION Middle-East and central-asia COUNTRIES

In [1]:
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("../data/Middle.csv")
data.dropna(inplace=True)

data

,Unnamed: 0,Country,Exports_2014,Exports_2015,Exports_2016,Exports_2017,Exports_2018,Exports_2019,Exports_2020,Exports_2021,...,Inflation_2022,Openness_2014,Openness_2015,Openness_2016,Openness_2017,Openness_2018,Openness_2019,Openness_2020,Openness_2021,Openness_2022
0,35,Algeria,20756.123822,19432.028414,21349.480843,22440.669772,24767.981118,22313.190543,18930.999731,21738.175626,...,9.265516,7.413764,7.913498,8.488628,8.840581,9.987054,9.541131,8.713855,9.327852,9.987732
1,36,"Armenia, Rep. of",2283.441925,1889.080869,1723.594089,2175.168005,2572.899726,3091.242090,2674.021158,3369.345418,...,8.640911,13.674089,13.069515,13.744608,15.672408,17.169618,19.033958,19.663961,22.549205,16.713145
2,37,"Azerbaijan, Rep. of",9631.518821,6553.144156,4542.387815,5505.451457,6612.914779,7236.480345,6725.201983,8253.265973,...,13.852259,11.460524,10.236400,10.725803,12.834973,11.968353,11.784587,12.425459,12.638057,9.703193
3,38,"Bahrain, Kingdom of",16299.394249,10716.136559,9265.244871,10056.821936,12434.575460,11763.620264,8759.920440,13717.785772,...,3.625741,37.746775,27.095067,22.400628,24.156973,28.378144,28.180039,24.836893,32.433279,35.171022
4,39,Djibouti,4362.804964,4247.167554,4478.201193,4740.001896,4760.888144,5614.510399,5021.691510,6890.334821,...,5.179808,102.296256,94.788031,88.999557,89.490015,85.330522,94.074255,82.489203,106.239895,132.766161
5,40,"Egypt, Arab Rep. of",44833.365899,40679.358512,39498.000396,40866.832443,45601.275941,45025.608115,41103.781748,58139.005899,...,13.895661,10.223938,8.465459,8.252429,11.982463,12.385686,10.325410,7.955189,9.791982,9.576045
6,41,Georgia,6371.393143,5383.246747,5407.004512,6000.084008,6591.491557,6975.930880,5967.763420,7491.816830,...,11.898165,23.087526,22.811863,22.119190,23.812383,24.040131,25.956373,31.169756,27.799827,24.429786
7,42,Iraq,31880.455776,26406.365284,22525.208545,27421.219053,26910.588432,28779.501150,27816.860719,31428.181225,...,4.994766,16.206193,16.405633,14.221944,16.507424,17.269007,17.290516,20.577894,22.138358,24.255437
8,43,Jordan,15686.096781,12173.833857,10510.952764,11449.639169,12578.127336,12612.404677,10699.097920,14612.632377,...,4.229156,28.996710,22.439356,19.175310,19.612932,20.295804,20.432031,18.713989,24.730557,31.276431
9,44,Kuwait,15631.427760,14633.534647,13152.491369,14418.916028,15148.258399,14797.677581,13519.304038,17631.589781,...,3.980650,18.134240,17.510880,15.364298,16.996496,19.834742,19.470430,19.722107,21.785408,21.959775
10,45,Kyrgyz Rep.,8645.647699,6760.784121,7845.875541,8365.259395,8692.259101,9815.484741,6219.516620,12296.804780,...,13.922909,63.657312,55.416981,63.019752,60.270427,57.703953,60.629046,45.617632,77.370440,101.215899
11,46,Libya,10378.287411,7184.743927,5192.462784,4949.803021,7526.897388,9263.967524,6396.398845,9082.508073,...,4.510301,11.115919,10.377260,8.845999,6.606126,9.820182,12.678515,11.210994,20.411510,19.854949
12,47,"Mauritania, Islamic Rep. of",2393.308001,2053.377715,2040.708006,2246.884039,2515.051888,2589.406445,2129.604444,3112.200234,...,9.525266,33.188532,27.264236,26.829522,27.766864,28.261083,26.028549,23.438293,30.440729,29.324173
13,48,Morocco,13097.533318,10818.501792,11097.587188,11928.273961,13593.119647,14777.297290,13465.246312,19526.695960,...,6.657042,8.773086,8.852735,8.344841,8.483343,8.909663,9.037994,8.953783,11.090161,14.714669
14,49,Oman,20833.019522,19947.082394,20278.009828,21816.901336,23625.797132,20679.759021,21531.826421,24089.322690,...,2.811841,30.579737,28.243744,27.426189,28.941451,31.388394,31.093954,33.487657,42.487570,44.992806
15,50,Pakistan,38520.900093,36058.054624,37684.381899,42841.496948,45025.358738,37975.086165,34661.300722,54423.455397,...,19.873860,10.443734,8.759526,7.598718,7.870638,7.992782,7.584266,7.391210,9.670957,9.428600
16,51,Qatar,13745.341645,11037.813291,9853.724601,10557.799957,10613.342488,9937.963595,10242.969678,12271.474426,...,4.995276,12.628644,11.406147,10.497140,11.880865,12.409422,11.489592,12.871313,14.997861,16.439647
17,52,Saudi Arabia,73319.646105,72978.789068,55202.389191,54636.745035,56392.903380,64450.019763,67298.930539,75585.108401,...,2.474074,15.014698,13.471406,10.689049,11.318874,11.699062,12.499199,11.603910,13.152062,14.119204
18,53,Sudan,6739.850255,6805.106026,5851.726149,7203.327357,6470.949958,7369.016066,7884.454511,7588.847536,...,138.808460,7.822066,5.993483,4.501830,4.634442,16.145737,17.025342,21.367188,18.417913,14.314921
19,54,Tunisia,8170.354688,6296.584996,5988.129576,6599.546324,7594.938722,7636.861617,6837.767232,8801.419699,...,8.306461,11.751108,10.126816,10.169138,13.361125,15.210396,14.418947,12.607827,13.822042,14.574751
20,55,United Arab Emirates,154425.441751,127981.499935,124681.630201,133299.247988,130059.386141,129662.637997,111589.253488,151676.269931,...,4.827889,35.068948,31.846331,30.750862,32.197467,30.659252,30.652236,31.465644,37.492070,39.225043
21,56,"Uzbekistan, Rep. of",9999.475058,7843.109995,6780.408353,8551.225065,11731.401383,14458.087587,15221.496960,18654.606375,...,11.446644,9.554834,7.190835,6.878781,11.567039,17.500988,17.875934,17.728833,19.666130,19.327694
22,57,West Bank and Gaza,510.423862,538.605562,485.379050,593.042207,574.901275,608.547760,657.539378,943.402665,...,3.741224,2.190866,2.274934,1.845460,2.171078,2.086816,2.132876,2.589800,2.993337,3.662185

In [3]:
data = data.drop(['Unnamed: 0', 'Country'], axis=1)

In [4]:
for year in range(2014, 2023):
    # Logarithmic transformation of the columns
    data[f'log_GDP_{year}'] = np.log(data[f'GDP_{year}'] + 1)
    data[f'log_Exports_{year}'] = np.log(data[f'Exports_{year}'] + 1)
    data[f'log_Imports_{year}'] = np.log(data[f'Imports_{year}'] + 1)
    data[f'log_Inflation_{year}'] = np.log(data[f'Inflation_{year}'] + 1)
    data[f'log_Openness_{year}'] = np.log(data[f'Openness_{year}'] + 1)

# Analyse for each year
for year in range(2014, 2023):
    cols = [f'log_Exports_{year}', f'log_Imports_{year}', f'log_Inflation_{year}', f'log_GDP_{year}']

    # Drop NA
    data_year = data.dropna(subset=cols)

    # Independent and dependent variables
    X = data_year[[f'log_Exports_{year}', f'log_Imports_{year}', f'log_Inflation_{year}', f'log_Openness_{year}']]
    Y = data_year[f'log_GDP_{year}']

    # Train and test split
    X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
    
    # Model
    model = LinearRegression()
    model.fit(X_train, y_train)

    # Prediction and evaluation
    y_pred = model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    print(f"Year: {year}")
    print("Coefficients:", model.coef_)
    print("Mean Squared Error (MSE):", mse)
    print("R-squared (R²):", r2)
    print()

Year: 2014
Coefficients: [ 0.65738234  0.30821741 -0.03367163 -0.99571282]
Mean Squared Error (MSE): 0.03172465444241445
R-squared (R²): 0.9665166476508593

Year: 2015
Coefficients: [ 0.71195217  0.28608878 -0.06333569 -1.08440122]
Mean Squared Error (MSE): 0.02701813045166307
R-squared (R²): 0.9696354132785657

Year: 2016
Coefficients: [ 0.78635539  0.20896722 -0.01042735 -1.06768294]
Mean Squared Error (MSE): 0.04047010721507869
R-squared (R²): 0.8567029083653308

Year: 2017
Coefficients: [ 0.75147517  0.25047941 -0.0551139  -1.07830371]
Mean Squared Error (MSE): 0.014595403126292646
R-squared (R²): 0.9841714969817524

Year: 2018
Coefficients: [ 0.69473763  0.30206383 -0.08894624 -1.0448439 ]
Mean Squared Error (MSE): 0.021059783922900508
R-squared (R²): 0.9785354240318551

Year: 2019
Coefficients: [ 0.7017343   0.27361196 -0.05795656 -1.00877426]
Mean Squared Error (MSE): 0.025871312258678617
R-squared (R²): 0.9773827638402562

Year: 2020
Coefficients: [ 0.72317679  0.27053401 -0.0354715  -0.99376957]
Mean Squared Error (MSE): 0.009444407489665048
R-squared (R²): 0.9958247765721802

Year: 2021
Coefficients: [ 0.65059402  0.31600314 -0.03130283 -0.97989601]
Mean Squared Error (MSE): 0.023425677150689387
R-squared (R²): 0.975929314835259

Year: 2022
Coefficients: [ 0.64227769  0.32846163 -0.06928716 -0.94031908]
Mean Squared Error (MSE): 0.03305138604543081
R-squared (R²): 0.968738381351799

C:\Users\Manjaka\anaconda3\lib\site-packages\pandas\core\arraylike.py:396: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\Manjaka\anaconda3\lib\site-packages\pandas\core\arraylike.py:396: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\Manjaka\anaconda3\lib\site-packages\pandas\core\arraylike.py:396: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [ ]:
for year in range(2014, 2023):
    plt.scatter(y_test, y_pred, alpha=0.5)
    plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'k--', lw=2)
    plt.xlabel('real values')
    plt.ylabel('Prediction')
    plt.title(f'Prediction vs values for {year}')
    plt.show()